"""change in in student

Revision ID: 1f86334f08de
Revises: 6df45c6acfc5
Create Date: 2025-11-18 16:48:37.174284

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f86334f08de'
down_revision = '6df45c6acfc5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Teacher', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_teacher_course'), type_='foreignkey')
        batch_op.drop_column('course_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Teacher', schema=None) as batch_op:
        batch_op.add_column(sa.Column('course_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_teacher_course'), 'Course', ['course_id'], ['id'])

    # ### end Alembic commands ###
