"""Initial migration

Revision ID: 2c05fccc8c13
Revises: 
Create Date: 2025-11-17 15:15:25.560224

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c05fccc8c13'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Course',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('Parent',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('password', sa.String(length=100), nullable=True),
    sa.Column('child_name', sa.String(length=100), nullable=True),
    sa.Column('relation_to_student', sa.String(length=50), nullable=True),
    sa.Column('address', sa.String(length=200), nullable=True),
    sa.Column('contact', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Subject',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('login',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('password', sa.String(length=100), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('Student',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('password', sa.String(length=100), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('grade', sa.String(length=10), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['Course.id'], name='fk_student_course'),
    sa.ForeignKeyConstraint(['parent_id'], ['Parent.id'], name='fk_student_parent'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('Teacher',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('photo', sa.String(length=200), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('password', sa.String(length=100), nullable=False),
    sa.Column('qualifications', sa.String(length=200), nullable=False),
    sa.Column('availability', sa.String(length=100), nullable=False),
    sa.Column('years_of_experience', sa.Integer(), nullable=False),
    sa.Column('contact', sa.String(length=15), nullable=False),
    sa.Column('place', sa.String(length=100), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['Course.id'], name='fk_teacher_course'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('Attendance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=True),
    sa.Column('teacher_id', sa.Integer(), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['Student.id'], ),
    sa.ForeignKeyConstraint(['teacher_id'], ['Teacher.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Live_class',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('teacher_id', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('time', sa.Time(), nullable=False),
    sa.Column('platform', sa.String(length=100), nullable=True),
    sa.Column('link', sa.String(length=300), nullable=False),
    sa.ForeignKeyConstraint(['subject_id'], ['Course.id'], name='fk_live_subject'),
    sa.ForeignKeyConstraint(['teacher_id'], ['Teacher.id'], name='fk_live_teacher'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Recorded_class',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('teacher_id', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('filename', sa.String(length=300), nullable=False),
    sa.ForeignKeyConstraint(['subject_id'], ['Course.id'], name='fk_record_subject'),
    sa.ForeignKeyConstraint(['teacher_id'], ['Teacher.id'], name='fk_record_teacher'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Studymaterial',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subject', sa.String(length=100), nullable=False),
    sa.Column('teacher_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('filename', sa.String(length=300), nullable=False),
    sa.Column('upload_date', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['teacher_id'], ['Teacher.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Progress',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=True),
    sa.Column('material_id', sa.Integer(), nullable=True),
    sa.Column('viewed', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['material_id'], ['Studymaterial.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['Student.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Progress')
    op.drop_table('Studymaterial')
    op.drop_table('Recorded_class')
    op.drop_table('Live_class')
    op.drop_table('Attendance')
    op.drop_table('Teacher')
    op.drop_table('Student')
    op.drop_table('login')
    op.drop_table('Subject')
    op.drop_table('Parent')
    op.drop_table('Course')
    # ### end Alembic commands ###
