"""change in in student

Revision ID: 6df45c6acfc5
Revises: ec23236a2b61
Create Date: 2025-11-18 16:45:07.026999

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6df45c6acfc5'
down_revision = 'ec23236a2b61'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Teacher', schema=None) as batch_op:
        batch_op.add_column(sa.Column('course', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Teacher', schema=None) as batch_op:
        batch_op.drop_column('course')

    # ### end Alembic commands ###
