"""initial

Revision ID: 80d939492a0a
Revises: 1f86334f08de
Create Date: 2025-11-19 15:14:32.367488

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '80d939492a0a'
down_revision = '1f86334f08de'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Teacher', schema=None) as batch_op:
        batch_op.add_column(sa.Column('course_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_teacher_course', 'Course', ['course_id'], ['id'])
        batch_op.drop_column('course')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Teacher', schema=None) as batch_op:
        batch_op.add_column(sa.Column('course', sa.VARCHAR(length=100), nullable=True))
        batch_op.drop_constraint('fk_teacher_course', type_='foreignkey')
        batch_op.drop_column('course_id')

    # ### end Alembic commands ###
