"""change in uploaded class

Revision ID: ec23236a2b61
Revises: b62f9ba34593
Create Date: 2025-11-18 16:03:03.766097

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ec23236a2b61'
down_revision = 'b62f9ba34593'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Live_class', schema=None) as batch_op:
        batch_op.add_column(sa.Column('course_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint(batch_op.f('fk_live_subject'), type_='foreignkey')
        batch_op.create_foreign_key('fk_live_subject', 'Course', ['course_id'], ['id'])
        batch_op.drop_column('subject_id')

    with op.batch_alter_table('Recorded_class', schema=None) as batch_op:
        batch_op.add_column(sa.Column('course_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint(batch_op.f('fk_record_subject'), type_='foreignkey')
        batch_op.create_foreign_key('fk_record_subject', 'Course', ['course_id'], ['id'])
        batch_op.drop_column('subject_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Recorded_class', schema=None) as batch_op:
        batch_op.add_column(sa.Column('subject_id', sa.INTEGER(), nullable=False))
        batch_op.drop_constraint('fk_record_subject', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_record_subject'), 'Course', ['subject_id'], ['id'])
        batch_op.drop_column('course_id')

    with op.batch_alter_table('Live_class', schema=None) as batch_op:
        batch_op.add_column(sa.Column('subject_id', sa.INTEGER(), nullable=False))
        batch_op.drop_constraint('fk_live_subject', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_live_subject'), 'Course', ['subject_id'], ['id'])
        batch_op.drop_column('course_id')

    # ### end Alembic commands ###
